import React from 'react';

export type AppLanguage = 'kk' | 'ru';

const translations = {
  kk: {
    accountId: 'Аккаунт ID',
    accountName: 'Аккаунт аты',
    all: 'Барлығы',
    alreadyAccount: 'Аккаунтыңыз бар ма? Кіру',
    apply: 'Қолдану',
    cancel: 'Болдырмау',
    category: 'Санат',
    categoryMissing: 'Санат жоқ',
    chat: 'Чат',
    chatEmpty: 'Әзірге хабар жоқ. Бірінші хабарды жазыңыз.',
    chatLocked: 'Чат ұйым тағайындалғаннан кейін ашылады.',
    chatLoading: 'Чат жүктелуде...',
    chatNotFound: 'Чат табылмады',
    city: 'Қала',
    cityMissing: 'Қала жоқ',
    clear: 'Тазалау',
    commentPlaceholder: 'Комментарий жазу',
    comments: 'Комментарийлер',
    createAccount: 'Аккаунт құру',
    createLoading: 'Құру беті жүктелуде...',
    createRequest: 'Жаңа өтінім',
    createdAt: 'Құрылған уақыты',
    currentPhoto: 'Қазіргі фото',
    dataLoadFailed: 'Деректер жүктелмеді.',
    delete: 'Өшіру',
    deletePhoto: 'Фотоны өшіру',
    description: 'Сипаттама',
    district: 'Аудан',
    emailPasswordRequired: 'Email және кемінде 8 таңбалы құпиясөз енгізіңіз',
    error: 'Қате',
    filters: 'Сүзгілер',
    fullName: 'Аты-жөні',
    high: 'Жоғары',
    inProgress: 'Орындалуда',
    issue: 'Өтінім',
    issueDescription: 'Мәселе сипаттамасы',
    issueOwner: 'Өтініш иесі',
    locationPermissionText: 'Орныңызды белгілеу үшін геолокацияға рұқсат беріңіз.',
    languageCode: 'ҚАЗ',
    loadingInfo: 'Ақпарат жүктелуде...',
    locationPoint: 'Орналасу нүктесі',
    login: 'Кіру',
    loginTitle: 'Аккаунтқа кіру',
    logout: 'Шығу',
    logoutConfirm: 'Аккаунттан шығуды растайсыз ба?',
    logoutTitle: 'Шығу',
    low: 'Төмен',
    mapLoading: 'Карта жүктеліп жатыр...',
    mapLoadFailed: 'Карта жүктелмеді',
    medium: 'Орташа',
    messageCount: 'хабар',
    messagePlaceholder: 'Хабар жазыңыз...',
    myLocation: 'Менің орным',
    newIssue: 'Жаңа мәселе',
    newPhoto: 'Жаңа фото',
    noAccount: 'Аккаунт жоқ па? Регистрация',
    noDescription: 'Сипаттама жоқ',
    noMessage: 'Хабар жоқ',
    notAssigned: 'Тағайындалмаған',
    notSelected: 'Таңдалмаған',
    notSpecified: 'Көрсетілмеген',
    onboardingNext: 'Далее',
    onboardingSkip: 'Пропустить',
    onboardingStart: 'Начать',
    onboardingTitle1: 'AIQala-ға қош келдіңіз',
    onboardingTitle2: 'Қалалық мәселені жылдам хабарлаңыз',
    onboardingTitle3: 'Өтінім статусын бақылаңыз',
    organization: 'Ұйым',
    organizationNotAssigned: 'Ұйым тағайындалмаған',
    organizationNotAssignedYet: 'Ұйым әлі тағайындалмаған',
    password: 'Құпиясөз',
    passwordHide: 'Құпиясөзді жасыру',
    passwordRepeat: 'Құпиясөзді қайталаңыз',
    passwordShow: 'Құпиясөзді көрсету',
    passwordsMismatch: 'Құпиясөздер сәйкес емес',
    permissionRequired: 'Рұқсат керек',
    photo: 'Фото',
    photoLimitText: 'Бір өтінімге максимум 3 фото қосылады.',
    photoPermissionText: 'Фото таңдау үшін галереяға рұқсат беріңіз.',
    photos: 'Фотолар',
    photoUpload: 'Басқасын жүктеу',
    pickPhoto: 'Фото таңдау',
    profile: 'Профиль',
    profilePhoto: 'Профиль фотосы',
    register: 'Тіркелу',
    requests: 'Өтінімдер',
    requestsLoading: 'Өтінімдер жүктелуде...',
    requestDeleteConfirm: 'Өтінімді өшіруді растайсыз ба?',
    requestDeleteFailed: 'Өтінімді өшіру мүмкін болмады.',
    requestFieldsIncomplete: 'Тақырып, сипаттама, санат және қала толық толтырылуы керек.',
    requestSaveFailed: 'Өтінімді сақтау мүмкін болмады.',
    requestSendFailed: 'Өтінімді жіберу мүмкін болмады.',
    requestsLoadFailed: 'Өтінімдерді жүктеу мүмкін болмады.',
    commentSendFailed: 'Комментарий жіберілмеді.',
    requestNotFound: 'Өтінім табылмады',
    resolved: 'Шешілді',
    retry: 'Қайталау',
    role: 'Рөл',
    save: 'Сақтау',
    searchRequest: 'Өтінімді іздеу',
    selectPhoto: 'Фото қосу',
    send: 'Жіберу',
    status: 'Статус',
    title: 'Тақырып',
    updateAvatar: 'Фото өзгерту',
    avatarDeleteFailed: 'Фотоны өшіру мүмкін болмады.',
    avatarUploadFailed: 'Фотоны жүктеу мүмкін болмады.',
    nameTooShort: 'Аккаунт аты кемінде 2 таңбадан тұруы керек.',
    nameUpdateFailed: 'Аккаунт атын өзгерту мүмкін болмады.',
    updateNameTitle: 'Аккаунт атын өзгерту',
    viewDetails: 'Толығырақ',
    you: 'Сіз',
    unknown: 'Белгісіз',
    unnamed: 'Есім енгізіңіз',
    descriptionTooShort: 'Сипаттама ең болмағанда 10 символ болуы керек',
    aiEnhance: 'ИИ жағдайлау',
    aiEnhanceFailed: 'Сипаттаманы жағдайлау сәтсіз болды',
  },
  ru: {
    accountId: 'ID аккаунта',
    accountName: 'Имя аккаунта',
    all: 'Все',
    alreadyAccount: 'Уже есть аккаунт? Войти',
    apply: 'Применить',
    cancel: 'Отмена',
    category: 'Категория',
    categoryMissing: 'Нет категории',
    chat: 'Чат',
    chatEmpty: 'Пока нет сообщений. Напишите первое сообщение.',
    chatLocked: 'Чат откроется после назначения организации.',
    chatLoading: 'Чат загружается...',
    chatNotFound: 'Чат не найден',
    city: 'Город',
    cityMissing: 'Нет города',
    clear: 'Очистить',
    commentPlaceholder: 'Написать комментарий',
    comments: 'Комментарии',
    createAccount: 'Создать аккаунт',
    createLoading: 'Страница создания загружается...',
    createRequest: 'Новая заявка',
    createdAt: 'Дата создания',
    currentPhoto: 'Текущие фото',
    dataLoadFailed: 'Данные не загрузились.',
    delete: 'Удалить',
    deletePhoto: 'Удалить фото',
    description: 'Описание',
    district: 'Район',
    emailPasswordRequired: 'Введите email и пароль минимум 8 символов',
    error: 'Ошибка',
    filters: 'Фильтры',
    fullName: 'Имя',
    high: 'Высокий',
    inProgress: 'В работе',
    issue: 'Заявка',
    issueDescription: 'Описание проблемы',
    issueOwner: 'Заявитель',
    locationPermissionText: 'Разрешите геолокацию, чтобы отметить ваше местоположение.',
    languageCode: 'РУС',
    loadingInfo: 'Информация загружается...',
    locationPoint: 'Точка на карте',
    login: 'Войти',
    loginTitle: 'Войти в аккаунт',
    logout: 'Выйти',
    logoutConfirm: 'Подтвердите выход из аккаунта',
    logoutTitle: 'Выход',
    low: 'Низкий',
    mapLoading: 'Карта загружается...',
    mapLoadFailed: 'Карта не загрузилась',
    medium: 'Средний',
    messageCount: 'сообщ.',
    messagePlaceholder: 'Напишите сообщение...',
    myLocation: 'Мое место',
    newIssue: 'Новая проблема',
    newPhoto: 'Новые фото',
    noAccount: 'Нет аккаунта? Регистрация',
    noDescription: 'Нет описания',
    noMessage: 'Нет сообщений',
    notAssigned: 'Не назначено',
    notSelected: 'Не выбрано',
    notSpecified: 'Не указано',
    onboardingNext: 'Далее',
    onboardingSkip: 'Пропустить',
    onboardingStart: 'Начать',
    onboardingTitle1: 'Добро пожаловать в AIQala',
    onboardingTitle2: 'Сообщайте о городских проблемах быстро',
    onboardingTitle3: 'Следите за статусом заявки',
    organization: 'Организация',
    organizationNotAssigned: 'Организация не назначена',
    organizationNotAssignedYet: 'Организация еще не назначена',
    password: 'Пароль',
    passwordHide: 'Скрыть пароль',
    passwordRepeat: 'Повторите пароль',
    passwordShow: 'Показать пароль',
    passwordsMismatch: 'Пароли не совпадают',
    permissionRequired: 'Нужно разрешение',
    photo: 'Фото',
    photoLimitText: 'К одной заявке можно добавить максимум 3 фото.',
    photoPermissionText: 'Разрешите доступ к галерее, чтобы выбрать фото.',
    photos: 'Фотографии',
    photoUpload: 'Загрузить другое',
    pickPhoto: 'Выбрать фото',
    profile: 'Профиль',
    profilePhoto: 'Фото профиля',
    register: 'Зарегистрироваться',
    requests: 'Заявки',
    requestsLoading: 'Заявки загружаются...',
    requestDeleteConfirm: 'Подтвердите удаление заявки',
    requestDeleteFailed: 'Не удалось удалить заявку.',
    requestFieldsIncomplete: 'Заполните заголовок, описание, категорию и город.',
    requestSaveFailed: 'Не удалось сохранить заявку.',
    requestSendFailed: 'Не удалось отправить заявку.',
    requestsLoadFailed: 'Не удалось загрузить заявки.',
    commentSendFailed: 'Комментарий не отправлен.',
    requestNotFound: 'Заявка не найдена',
    resolved: 'Решено',
    retry: 'Повторить',
    role: 'Роль',
    save: 'Сохранить',
    searchRequest: 'Поиск заявки',
    selectPhoto: 'Добавить фото',
    send: 'Отправить',
    status: 'Статус',
    title: 'Заголовок',
    updateAvatar: 'Изменить фото',
    avatarDeleteFailed: 'Не удалось удалить фото.',
    avatarUploadFailed: 'Не удалось загрузить фото.',
    nameTooShort: 'Имя аккаунта должно содержать минимум 2 символа.',
    nameUpdateFailed: 'Не удалось изменить имя аккаунта.',
    updateNameTitle: 'Изменить имя аккаунта',
    viewDetails: 'Подробнее',
    you: 'Вы',
    unknown: 'Неизвестно',
    unnamed: 'Введите имя',
    descriptionTooShort: 'Описание должно содержать минимум 10 символов',
    aiEnhance: 'Улучшение ИИ',
    aiEnhanceFailed: 'Не удалось улучшить описание',
  },
} as const;

export type TranslationKey = keyof typeof translations.kk;

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = React.createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = React.useState<AppLanguage>('kk');

  const value = React.useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'kk' ? 'ru' : 'kk')),
      t: (key) => translations[language][key],
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = React.useContext(LanguageContext);

  if (!value) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return value;
}
